site_name: Office 365 CLI
nav:
  - Home: 'index.md'
  - User Guide:
    - 'Installing the CLI': 'user-guide/installing-cli.md'
    - 'Using the CLI': 'user-guide/using-cli.md'
    - 'Logging in to Office 365': 'user-guide/connecting-office-365.md'
    - 'CLI output mode': 'user-guide/cli-output-mode.md'
  - Commands:
    - SharePoint Online (spo):
      - login: 'cmd/spo/login.md'
      - logout: 'cmd/spo/logout.md'
      - status: 'cmd/spo/status.md'
      - app:
        - app add: 'cmd/spo/app/app-add.md'
        - app deploy: 'cmd/spo/app/app-deploy.md'
        - app get: 'cmd/spo/app/app-get.md'
        - app install: 'cmd/spo/app/app-install.md'
        - app list: 'cmd/spo/app/app-list.md'
        - app remove: 'cmd/spo/app/app-remove.md'
        - app retract: 'cmd/spo/app/app-retract.md'
        - app uninstall: 'cmd/spo/app/app-uninstall.md'
        - app upgrade: 'cmd/spo/app/app-upgrade.md'
      - cdn:
        - cdn get: 'cmd/spo/cdn/cdn-get.md'
        - cdn origin add: 'cmd/spo/cdn/cdn-origin-add.md'
        - cdn origin list: 'cmd/spo/cdn/cdn-origin-list.md'
        - cdn origin remove: 'cmd/spo/cdn/cdn-origin-remove.md'
        - cdn policy list: 'cmd/spo/cdn/cdn-policy-list.md'
        - cdn policy set: 'cmd/spo/cdn/cdn-policy-set.md'
        - cdn set: 'cmd/spo/cdn/cdn-set.md'
      - contenttype:
        - contenttype add: 'cmd/spo/contenttype/contenttype-add.md'
        - contenttype get: 'cmd/spo/contenttype/contenttype-get.md'
        - contenttype field remove: 'cmd/spo/contenttype/contenttype-field-remove.md'
        - contenttype field set: 'cmd/spo/contenttype/contenttype-field-set.md'
      - customaction:
        - customaction add: 'cmd/spo/customaction/customaction-add.md'
        - customaction clear: 'cmd/spo/customaction/customaction-clear.md'
        - customaction get: 'cmd/spo/customaction/customaction-get.md'
        - customaction list: 'cmd/spo/customaction/customaction-list.md'
        - customaction remove: 'cmd/spo/customaction/customaction-remove.md'
        - customaction set: 'cmd/spo/customaction/customaction-set.md'
      - externaluser:
        - externaluser list: 'cmd/spo/externaluser/externaluser-list.md'
      - feature:
        - feature list: 'cmd/spo/feature/feature-list.md'
      - field:
        - field add: 'cmd/spo/field/field-add.md'
        - field get: 'cmd/spo/field/field-get.md'
        - field remove: 'cmd/spo/field/field-remove.md'
        - field set: 'cmd/spo/field/field-set.md'
      - file:
        - file add: 'cmd/spo/file/file-add.md'
        - file checkin: 'cmd/spo/file/file-checkin.md'
        - file checkout: 'cmd/spo/file/file-checkout.md'
        - file copy: 'cmd/spo/file/file-copy.md'
        - file get: 'cmd/spo/file/file-get.md'
        - file list: 'cmd/spo/file/file-list.md'
        - file move: 'cmd/spo/file/file-move.md'
        - file remove: 'cmd/spo/file/file-remove.md'
      - folder:
        - folder add: 'cmd/spo/folder/folder-add.md'
        - folder copy: 'cmd/spo/folder/folder-copy.md'
        - folder get: 'cmd/spo/folder/folder-get.md'
        - folder list: 'cmd/spo/folder/folder-list.md'
        - folder move: 'cmd/spo/folder/folder-move.md'
        - folder remove: 'cmd/spo/folder/folder-remove.md'
        - folder rename: 'cmd/spo/folder/folder-rename.md'
      - hidedefaultthemes:
        - hidedefaultthemes get: 'cmd/spo/hidedefaultthemes/hidedefaultthemes-get.md'
        - hidedefaultthemes set: 'cmd/spo/hidedefaultthemes/hidedefaultthemes-set.md'
      - hubsite:
        - hubsite connect: 'cmd/spo/hubsite/hubsite-connect.md'
        - hubsite data get: 'cmd/spo/hubsite/hubsite-data-get.md'
        - hubsite disconnect: 'cmd/spo/hubsite/hubsite-disconnect.md'
        - hubsite get: 'cmd/spo/hubsite/hubsite-get.md'
        - hubsite list: 'cmd/spo/hubsite/hubsite-list.md'
        - hubsite register: 'cmd/spo/hubsite/hubsite-register.md'
        - hubsite rights grant: 'cmd/spo/hubsite/hubsite-rights-grant.md'
        - hubsite rights revoke: 'cmd/spo/hubsite/hubsite-rights-revoke.md'
        - hubsite set: 'cmd/spo/hubsite/hubsite-set.md'
        - hubsite theme sync: 'cmd/spo/hubsite/hubsite-theme-sync.md'
        - hubsite unregister: 'cmd/spo/hubsite/hubsite-unregister.md'
      - list:
        - list add: 'cmd/spo/list/list-add.md'
        - list get: 'cmd/spo/list/list-get.md'
        - list list: 'cmd/spo/list/list-list.md'
        - list remove: 'cmd/spo/list/list-remove.md'
        - list set: 'cmd/spo/list/list-set.md'
        - list contenttype add: 'cmd/spo/list/list-contenttype-add.md'
        - list contenttype list: 'cmd/spo/list/list-contenttype-list.md'
        - list contenttype remove: 'cmd/spo/list/list-contenttype-remove.md'
        - list label get: 'cmd/spo/list/list-label-get.md'
        - list label set: 'cmd/spo/list/list-label-set.md'
        - list sitescript get: 'cmd/spo/list/list-sitescript-get.md'
        - list view get: 'cmd/spo/list/list-view-get.md'
        - list view list: 'cmd/spo/list/list-view-list.md'
        - list view remove: 'cmd/spo/list/list-view-remove.md'
        - list view set: 'cmd/spo/list/list-view-set.md'
        - list view field add: 'cmd/spo/list/list-view-field-add.md'
        - list view field remove: 'cmd/spo/list/list-view-field-remove.md'
        - list webhook add: 'cmd/spo/list/list-webhook-add.md'
        - list webhook get: 'cmd/spo/list/list-webhook-get.md'
        - list webhook list: 'cmd/spo/list/list-webhook-list.md'
        - list webhook remove: 'cmd/spo/list/list-webhook-remove.md'
        - list webhook set: 'cmd/spo/list/list-webhook-set.md'
      - listitem:
        - listitem add: 'cmd/spo/listitem/listitem-add.md'
        - listitem get: 'cmd/spo/listitem/listitem-get.md'
        - listitem list: 'cmd/spo/listitem/listitem-list.md'
        - listitem remove: 'cmd/spo/listitem/listitem-remove.md'
        - listitem set: 'cmd/spo/listitem/listitem-set.md'
        - listitem record declare: 'cmd/spo/listitem/listitem-record-declare.md'
        - listitem record undeclare: 'cmd/spo/listitem/listitem-record-undeclare.md'
      - mail:
        - mail send: 'cmd/spo/mail/mail-send.md'
      - navigation:
        - navigation node add: 'cmd/spo/navigation/navigation-node-add.md'
        - navigation node list: 'cmd/spo/navigation/navigation-node-list.md'
        - navigation node remove: 'cmd/spo/navigation/navigation-node-remove.md'
      - page:
        - page add: 'cmd/spo/page/page-add.md'
        - page get: 'cmd/spo/page/page-get.md'
        - page list: 'cmd/spo/page/page-list.md'
        - page remove: 'cmd/spo/page/page-remove.md'
        - page set: 'cmd/spo/page/page-set.md'
        - page clientsidewebpart add: 'cmd/spo/page/page-clientsidewebpart-add.md'
        - page column get: 'cmd/spo/page/page-column-get.md'
        - page column list: 'cmd/spo/page/page-column-list.md'
        - page control get: 'cmd/spo/page/page-control-get.md'
        - page control list: 'cmd/spo/page/page-control-list.md'
        - page header set: 'cmd/spo/page/page-header-set.md'
        - page section add: 'cmd/spo/page/page-section-add.md'
        - page section get: 'cmd/spo/page/page-section-get.md'
        - page section list: 'cmd/spo/page/page-section-list.md'
        - page text add: 'cmd/spo/page/page-text-add.md'
      - propertybag:
        - propertybag get: 'cmd/spo/propertybag/propertybag-get.md'
        - propertybag list: 'cmd/spo/propertybag/propertybag-list.md'
        - propertybag remove: 'cmd/spo/propertybag/propertybag-remove.md'
        - propertybag set: 'cmd/spo/propertybag/propertybag-set.md'
      - search:
        - search: 'cmd/spo/search/search.md'
      - serviceprincipal:
        - serviceprincipal grant add: 'cmd/spo/serviceprincipal/serviceprincipal-grant-add.md'
        - serviceprincipal grant list: 'cmd/spo/serviceprincipal/serviceprincipal-grant-list.md'
        - serviceprincipal grant revoke: 'cmd/spo/serviceprincipal/serviceprincipal-grant-revoke.md'
        - serviceprincipal permissionrequest approve: 'cmd/spo/serviceprincipal/serviceprincipal-permissionrequest-approve.md'
        - serviceprincipal permissionrequest deny: 'cmd/spo/serviceprincipal/serviceprincipal-permissionrequest-deny.md'
        - serviceprincipal permissionrequest list: 'cmd/spo/serviceprincipal/serviceprincipal-permissionrequest-list.md'
        - serviceprincipal set: 'cmd/spo/serviceprincipal/serviceprincipal-set.md'
      - site:
        - site add: 'cmd/spo/site/site-add.md'
        - site get: 'cmd/spo/site/site-get.md'
        - site list: 'cmd/spo/site/site-list.md'
        - site set: 'cmd/spo/site/site-set.md'
        - site appcatalog add: 'cmd/spo/site/site-appcatalog-add.md'
        - site appcatalog remove: 'cmd/spo/site/site-appcatalog-remove.md'
        - site classic add: 'cmd/spo/site/site-classic-add.md'
        - site classic list: 'cmd/spo/site/site-classic-list.md'
        - site classic remove: 'cmd/spo/site/site-classic-remove.md'
        - site classic set: 'cmd/spo/site/site-classic-set.md'
        - site groupify: 'cmd/spo/site/site-o365group-set.md'
        - site inplacerecordsmanagement set: 'cmd/spo/site/site-inplacerecordsmanagement-set.md'
        - site o365group set: 'cmd/spo/site/site-o365group-set.md'
      - sitedesign:
        - sitedesign add: 'cmd/spo/sitedesign/sitedesign-add.md'
        - sitedesign apply: 'cmd/spo/sitedesign/sitedesign-apply.md'
        - sitedesign get: 'cmd/spo/sitedesign/sitedesign-get.md'
        - sitedesign list: 'cmd/spo/sitedesign/sitedesign-list.md'
        - sitedesign remove: 'cmd/spo/sitedesign/sitedesign-remove.md'
        - sitedesign set: 'cmd/spo/sitedesign/sitedesign-set.md'
        - sitedesign rights grant: 'cmd/spo/sitedesign/sitedesign-rights-grant.md'
        - sitedesign rights list: 'cmd/spo/sitedesign/sitedesign-rights-list.md'
        - sitedesign rights revoke: 'cmd/spo/sitedesign/sitedesign-rights-revoke.md'
        - sitedesign run list: 'cmd/spo/sitedesign/sitedesign-run-list.md'
        - sitedesign run status get: 'cmd/spo/sitedesign/sitedesign-run-status-get.md'
        - sitedesign task get: 'cmd/spo/sitedesign/sitedesign-task-get.md'
        - sitedesign task list: 'cmd/spo/sitedesign/sitedesign-task-list.md'
      - sitescript:
        - sitescript add: 'cmd/spo/sitescript/sitescript-add.md'
        - sitescript get: 'cmd/spo/sitescript/sitescript-get.md'
        - sitescript list: 'cmd/spo/sitescript/sitescript-list.md'
        - sitescript remove: 'cmd/spo/sitescript/sitescript-remove.md'
        - sitescript set: 'cmd/spo/sitescript/sitescript-set.md'
      - storageentity:
        - storageentity get: 'cmd/spo/storageentity/storageentity-get.md'
        - storageentity list: 'cmd/spo/storageentity/storageentity-list.md'
        - storageentity remove: 'cmd/spo/storageentity/storageentity-remove.md'
        - storageentity set: 'cmd/spo/storageentity/storageentity-set.md'
      - tenant:
        - tenant appcatalogurl get: 'cmd/spo/tenant/tenant-appcatalogurl-get.md'
        - tenant settings list: 'cmd/spo/tenant/tenant-settings-list.md'
        - tenant settings set: 'cmd/spo/tenant/tenant-settings-set.md'
      - term:
        - term add: 'cmd/spo/term/term-add.md'
        - term get: 'cmd/spo/term/term-get.md'
        - term list: 'cmd/spo/term/term-list.md'
        - term group add: 'cmd/spo/term/term-group-add.md'
        - term group get: 'cmd/spo/term/term-group-get.md'
        - term group list: 'cmd/spo/term/term-group-list.md'
        - term set add: 'cmd/spo/term/term-set-add.md'
        - term set get: 'cmd/spo/term/term-set-get.md'
        - term set list: 'cmd/spo/term/term-set-list.md'
      - theme:
        - theme apply: 'cmd/spo/theme/theme-apply.md'
        - theme get: 'cmd/spo/theme/theme-get.md'
        - theme list: 'cmd/spo/theme/theme-list.md'
        - theme remove: 'cmd/spo/theme/theme-remove.md'
        - theme set: 'cmd/spo/theme/theme-set.md'
      - web:
        - web add: 'cmd/spo/web/web-add.md'
        - web clientsidewebpart list: 'cmd/spo/web/web-clientsidewebpart-list.md'
        - web get: 'cmd/spo/web/web-get.md'
        - web list: 'cmd/spo/web/web-list.md'
        - web reindex: 'cmd/spo/web/web-reindex.md'
        - web remove: 'cmd/spo/web/web-remove.md'
        - web set: 'cmd/spo/web/web-set.md'
    - SharePoint Framework (spfx):
      - project:
        - project upgrade: 'cmd/spfx/project/project-upgrade.md'
    - Microsoft Graph (graph):
      - login: 'cmd/graph/login.md'
      - logout: 'cmd/graph/logout.md'
      - status: 'cmd/graph/status.md'
      - groupsetting:
        - groupsetting add: 'cmd/graph/groupsetting/groupsetting-add.md'
        - groupsetting get: 'cmd/graph/groupsetting/groupsetting-get.md'
        - groupsetting list: 'cmd/graph/groupsetting/groupsetting-list.md'
        - groupsetting remove: 'cmd/graph/groupsetting/groupsetting-remove.md'
        - groupsetting set: 'cmd/graph/groupsetting/groupsetting-set.md'
      - groupsettingtemplate:
        - groupsettingtemplate get: 'cmd/graph/groupsettingtemplate/groupsettingtemplate-get.md'
        - groupsettingtemplate list: 'cmd/graph/groupsettingtemplate/groupsettingtemplate-list.md'
      - o365group:
        - o365group add: 'cmd/graph/o365group/o365group-add.md'
        - o365group get: 'cmd/graph/o365group/o365group-get.md'
        - o365group list: 'cmd/graph/o365group/o365group-list.md'
        - o365group remove: 'cmd/graph/o365group/o365group-remove.md'
        - o365group restore: 'cmd/graph/o365group/o365group-restore.md'
        - o365group set: 'cmd/graph/o365group/o365group-set.md'
        - o365group user add: 'cmd/graph/o365group/o365group-user-add.md'
      - schemaextension:
        - schemaextension add: 'cmd/graph/schemaextension/schemaextension-add.md'
      - siteclassification:
        - siteclassification disable: 'cmd/graph/siteclassification/siteclassification-disable.md'
        - siteclassification enable: 'cmd/graph/siteclassification/siteclassification-enable.md'
        - siteclassification get: 'cmd/graph/siteclassification/siteclassification-get.md'
        - siteclassification set: 'cmd/graph/siteclassification/siteclassification-set.md'
      - teams:
        - teams add: 'cmd/graph/teams/teams-add.md'
        - teams list: 'cmd/graph/teams/teams-list.md'
        - teams unarchive: 'cmd/graph/teams/teams-unarchive.md' 
        - teams app install: 'cmd/graph/teams/teams-app-install.md'
        - teams app list: 'cmd/graph/teams/teams-app-list.md'
        - teams app publish: 'cmd/graph/teams/teams-app-publish.md'
        - teams app remove: 'cmd/graph/teams/teams-app-remove.md'
        - teams app uninstall: 'cmd/graph/teams/teams-app-uninstall.md'
        - teams app update: 'cmd/graph/teams/teams-app-update.md'
        - teams channel add: 'cmd/graph/teams/teams-channel-add.md'
        - teams channel get: 'cmd/graph/teams/teams-channel-get.md'
        - teams channel list: 'cmd/graph/teams/teams-channel-list.md'
        - teams channel set: 'cmd/graph/teams/teams-channel-set.md'
        - teams funsettings list: 'cmd/graph/teams/teams-funsettings-list.md'
        - teams guestsettings list: 'cmd/graph/teams/teams-guestsettings-list.md'
        - teams guestsettings set: 'cmd/graph/teams/teams-guestsettings-set.md'
        - teams membersettings list: 'cmd/graph/teams/teams-membersettings-list.md'
        - teams membersettings set: 'cmd/graph/teams/teams-membersettings-set.md'
        - teams message get: 'cmd/graph/teams/teams-message-get.md'
        - teams message list: 'cmd/graph/teams/teams-message-list.md'
        - teams membersettings list: 'cmd/graph/teams/teams-membersettings-list.md'
        - teams messagingsettings list: 'cmd/graph/teams/teams-messagingsettings-list.md'
        - teams messagingsettings set: 'cmd/graph/teams/teams-messagingsettings-set.md'
        - teams tab list: 'cmd/graph/teams/teams-tab-list.md'
        - teams user add: 'cmd/graph/o365group/o365group-user-add.md'
        - teams user list: 'cmd/graph/teams/teams-user-list.md'
        - teams user remove: 'cmd/graph/teams/teams-user-remove.md'
        - teams user set: 'cmd/graph/teams/teams-user-set.md'
      - user:
        - user get: 'cmd/graph/user/user-get.md'
        - user list: 'cmd/graph/user/user-list.md'
        - user sendmail: 'cmd/graph/user/user-sendmail.md'
    - Azure Management Service (azmgmt):
      - login: 'cmd/azmgmt/login.md'
      - logout: 'cmd/azmgmt/logout.md'
      - status: 'cmd/azmgmt/status.md'
      - flow:
        - flow environment get: 'cmd/azmgmt/flow/flow-environment-get.md'
        - flow environment list: 'cmd/azmgmt/flow/flow-environment-list.md'
        - flow export: 'cmd/azmgmt/flow/flow-export.md'
        - flow get: 'cmd/azmgmt/flow/flow-get.md'
        - flow list: 'cmd/azmgmt/flow/flow-list.md'
        - flow run get: 'cmd/azmgmt/flow/flow-run-get.md'
        - flow run list: 'cmd/azmgmt/flow/flow-run-list.md'
    - Azure Active Directory Graph (aad):
      - login: 'cmd/aad/login.md'
      - logout: 'cmd/aad/logout.md'
      - status: 'cmd/aad/status.md'
      - oauth2grant:
        - oauth2grant add: 'cmd/aad/oauth2grant/oauth2grant-add.md'
        - oauth2grant list: 'cmd/aad/oauth2grant/oauth2grant-list.md'
        - oauth2grant remove: 'cmd/aad/oauth2grant/oauth2grant-remove.md'
        - oauth2grant set: 'cmd/aad/oauth2grant/oauth2grant-set.md'
      - service principal (sp):
        - sp get: 'cmd/aad/sp/sp-get.md'
  - Concepts:
    - 'Persisting connection': 'concepts/persisting-connection.md'
    - 'Authorization and access tokens': 'concepts/authorization-tokens.md'
    - 'Command completion': 'concepts/completion.md'
    - 'Communication with Office 365': 'concepts/communicating-o365.md'
  - About:
    - 'Why this CLI': 'about/why-cli.md'
    - 'Comparison to SharePoint and Office 365 PowerShell': 'about/comparison-powershell.md'
    - 'Release notes': 'about/release-notes.md'
    - License: 'about/license.md'
theme:
  name: 'material'
  palette:
    primary: 'red'
  logo: 'images/pnp-office365-cli-white.svg'
  feature:
    tabs: true
google_analytics:
  - 'UA-110480857-1'
  - 'auto'
extra_css:
  - 'css/styles.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: http://github.com/pnp/office365-cli
edit_uri: blob/master/docs/manual/docs
