site_name: Office 365 CLI
pages:
  - Home: 'index.md'
  - User Guide:
    - 'Installing the CLI': 'user-guide/installing-cli.md'
    - 'Using the CLI': 'user-guide/using-cli.md'
    - 'Connecting to Office 365': 'user-guide/connecting-office-365.md'
    - 'CLI output mode': 'user-guide/cli-output-mode.md'
  - Commands:
    - SharePoint Online (spo):
      - connect: 'cmd/spo/connect.md'
      - disconnect: 'cmd/spo/disconnect.md'
      - status: 'cmd/spo/status.md'
      - app:
        - app add: 'cmd/spo/app/app-add.md'
        - app deploy: 'cmd/spo/app/app-deploy.md'
        - app get: 'cmd/spo/app/app-get.md'
        - app install: 'cmd/spo/app/app-install.md'
        - app list: 'cmd/spo/app/app-list.md'
        - app remove: 'cmd/spo/app/app-remove.md'
        - app retract: 'cmd/spo/app/app-retract.md'
        - app uninstall: 'cmd/spo/app/app-uninstall.md'
        - app upgrade: 'cmd/spo/app/app-upgrade.md'
      - cdn:
        - cdn get: 'cmd/spo/cdn/cdn-get.md'
        - cdn origin add: 'cmd/spo/cdn/cdn-origin-add.md'
        - cdn origin list: 'cmd/spo/cdn/cdn-origin-list.md'
        - cdn origin remove: 'cmd/spo/cdn/cdn-origin-remove.md'
        - cdn policy list: 'cmd/spo/cdn/cdn-policy-list.md'
        - cdn policy set: 'cmd/spo/cdn/cdn-policy-set.md'
        - cdn set: 'cmd/spo/cdn/cdn-set.md'
      - customaction:
        - customaction add: 'cmd/spo/customaction/customaction-add.md'
        - customaction clear: 'cmd/spo/customaction/customaction-clear.md'
        - customaction get: 'cmd/spo/customaction/customaction-get.md'
        - customaction list: 'cmd/spo/customaction/customaction-list.md'
        - customaction remove: 'cmd/spo/customaction/customaction-remove.md'
        - customaction set: 'cmd/spo/customaction/customaction-set.md'
      - externaluser:
        - externaluser list: 'cmd/spo/externaluser/externaluser-list.md'
      - file:
        - file get: 'cmd/spo/file/file-get.md'
        - file list: 'cmd/spo/file/file-list.md'
        - file remove: 'cmd/spo/file/file-remove.md'
      - hubsite:
        - hubsite connect: 'cmd/spo/hubsite/hubsite-connect.md'
        - hubsite data get: 'cmd/spo/hubsite/hubsite-data-get.md'
        - hubsite disconnect: 'cmd/spo/hubsite/hubsite-disconnect.md'
        - hubsite get: 'cmd/spo/hubsite/hubsite-get.md'
        - hubsite list: 'cmd/spo/hubsite/hubsite-list.md'
        - hubsite register: 'cmd/spo/hubsite/hubsite-register.md'
        - hubsite rights grant: 'cmd/spo/hubsite/hubsite-rights-grant.md'
        - hubsite rights revoke: 'cmd/spo/hubsite/hubsite-rights-revoke.md'
        - hubsite set: 'cmd/spo/hubsite/hubsite-set.md'
        - hubsite theme sync: 'cmd/spo/hubsite/hubsite-theme-sync.md'
        - hubsite unregister: 'cmd/spo/hubsite/hubsite-unregister.md'
      - list:
        - list add: 'cmd/spo/list/list-add.md'
        - list get: 'cmd/spo/list/list-get.md'
        - list list: 'cmd/spo/list/list-list.md'
        - list remove: 'cmd/spo/list/list-remove.md'
        - list set: 'cmd/spo/list/list-set.md'
      - listitem:
        - listitem add: 'cmd/spo/listitem/listitem-add.md'
        - listitem remove: 'cmd/spo/listitem/listitem-remove.md'
      - page:
        - page add: 'cmd/spo/page/page-add.md'
        - page control get: 'cmd/spo/page/page-control-get.md'
        - page control list: 'cmd/spo/page/page-control-list.md'
        - page get: 'cmd/spo/page/page-get.md'
        - page list: 'cmd/spo/page/page-list.md'
        - page set: 'cmd/spo/page/page-set.md'
      - propertybag:
        - propertybag get: 'cmd/spo/propertybag/propertybag-get.md'
        - propertybag list: 'cmd/spo/propertybag/propertybag-list.md'
        - propertybag remove: 'cmd/spo/propertybag/propertybag-remove.md'
        - propertybag set: 'cmd/spo/propertybag/propertybag-set.md'
      - serviceprincipal:
        - serviceprincipal grant list: 'cmd/spo/serviceprincipal/serviceprincipal-grant-list.md'
        - serviceprincipal grant revoke: 'cmd/spo/serviceprincipal/serviceprincipal-grant-revoke.md'
        - serviceprincipal permissionrequest approve: 'cmd/spo/serviceprincipal/serviceprincipal-permissionrequest-approve.md'
        - serviceprincipal permissionrequest deny: 'cmd/spo/serviceprincipal/serviceprincipal-permissionrequest-deny.md'
        - serviceprincipal permissionrequest list: 'cmd/spo/serviceprincipal/serviceprincipal-permissionrequest-list.md'
        - serviceprincipal set: 'cmd/spo/serviceprincipal/serviceprincipal-set.md'
      - site:
        - site add: 'cmd/spo/site/site-add.md'
        - site get: 'cmd/spo/site/site-get.md'
        - site list: 'cmd/spo/site/site-list.md'
        - site set: 'cmd/spo/site/site-set.md'
        - site appcatalog add: 'cmd/spo/site/site-appcatalog-add.md'
        - site appcatalog remove: 'cmd/spo/site/site-appcatalog-remove.md'
        - site classic add: 'cmd/spo/site/site-classic-add.md'
        - site classic list: 'cmd/spo/site/site-classic-list.md'
        - site classic set: 'cmd/spo/site/site-classic-set.md'
      - sitedesign:
        - sitedesign add: 'cmd/spo/sitedesign/sitedesign-add.md'
        - sitedesign apply: 'cmd/spo/sitedesign/sitedesign-apply.md'
        - sitedesign get: 'cmd/spo/sitedesign/sitedesign-get.md'
        - sitedesign list: 'cmd/spo/sitedesign/sitedesign-list.md'
        - sitedesign remove: 'cmd/spo/sitedesign/sitedesign-remove.md'
        - sitedesign set: 'cmd/spo/sitedesign/sitedesign-set.md'
        - sitedesign rights grant: 'cmd/spo/sitedesign/sitedesign-rights-grant.md'
        - sitedesign rights list: 'cmd/spo/sitedesign/sitedesign-rights-list.md'
        - sitedesign rights revoke: 'cmd/spo/sitedesign/sitedesign-rights-revoke.md'
      - sitescript:
        - sitescript add: 'cmd/spo/sitescript/sitescript-add.md'
        - sitescript get: 'cmd/spo/sitescript/sitescript-get.md'
        - sitescript list: 'cmd/spo/sitescript/sitescript-list.md'
        - sitescript remove: 'cmd/spo/sitescript/sitescript-remove.md'
        - sitescript set: 'cmd/spo/sitescript/sitescript-set.md'
      - storageentity:
        - storageentity get: 'cmd/spo/storageentity/storageentity-get.md'
        - storageentity list: 'cmd/spo/storageentity/storageentity-list.md'
        - storageentity remove: 'cmd/spo/storageentity/storageentity-remove.md'
        - storageentity set: 'cmd/spo/storageentity/storageentity-set.md'
      - tenant:
        - tenant appcatalogurl get: 'cmd/spo/tenant/tenant-appcatalogurl-get.md'
      - theme:
        - theme get: 'cmd/spo/theme/theme-get.md'
        - theme list: 'cmd/spo/theme/theme-list.md'
        - theme remove: 'cmd/spo/theme/theme-remove.md'
        - theme set: 'cmd/spo/theme/theme-set.md'
      - web:
        - web add: 'cmd/spo/web/web-add.md'
        - web clientsidewebpart list: 'cmd/spo/web/web-clientsidewebpart-list.md'
        - web get: 'cmd/spo/web/web-get.md'
        - web list: 'cmd/spo/web/web-list.md'
        - web remove: 'cmd/spo/web/web-remove.md'
    - Microsoft Graph (graph):
      - connect: 'cmd/graph/connect.md'
      - disconnect: 'cmd/graph/disconnect.md'
      - status: 'cmd/graph/status.md'
      - o365group:
        - o365group add: 'cmd/graph/o365group/o365group-add.md'
        - o365group get: 'cmd/graph/o365group/o365group-get.md'
        - o365group list: 'cmd/graph/o365group/o365group-list.md'
        - o365group remove: 'cmd/graph/o365group/o365group-remove.md'
        - o365group restore: 'cmd/graph/o365group/o365group-restore.md'
        - o365group set: 'cmd/graph/o365group/o365group-set.md'
      - siteclassification:
        - siteclassification get: 'cmd/graph/siteclassification/siteclassification-get.md'
      - user:
        - user get: 'cmd/graph/user/user-get.md'
        - user list: 'cmd/graph/user/user-list.md'
    - Azure Management Service (azmgmt):
      - connect: 'cmd/azmgmt/connect.md'
      - disconnect: 'cmd/azmgmt/disconnect.md'
      - status: 'cmd/azmgmt/status.md'
      - flow:
        - flow environment get: 'cmd/azmgmt/flow/flow-environment-get.md'
        - flow environment list: 'cmd/azmgmt/flow/flow-environment-list.md'
        - flow get: 'cmd/azmgmt/flow/flow-get.md'
        - flow list: 'cmd/azmgmt/flow/flow-list.md'
    - Azure Active Directory Graph (aad):
      - connect: 'cmd/aad/connect.md'
      - disconnect: 'cmd/aad/disconnect.md'
      - status: 'cmd/aad/status.md'
      - oauth2grant:
        - oauth2grant add: 'cmd/aad/oauth2grant/oauth2grant-add.md'
        - oauth2grant list: 'cmd/aad/oauth2grant/oauth2grant-list.md'
        - oauth2grant remove: 'cmd/aad/oauth2grant/oauth2grant-remove.md'
        - oauth2grant set: 'cmd/aad/oauth2grant/oauth2grant-set.md'
      - service principal (sp):
        - sp get: 'cmd/aad/sp/sp-get.md'
  - Concepts:
    - 'Persisting connection': 'concepts/persisting-connection.md'
    - 'Authorization and access tokens': 'concepts/authorization-tokens.md'
    - 'Command completion': 'concepts/completion.md'
    - 'Communication with Office 365': 'concepts/communicating-o365.md'
  - About:
    - 'Why this CLI': 'about/why-cli.md'
    - 'Comparison to SharePoint PowerShell': 'about/comparison-powershell.md'
    - 'Release notes': 'about/release-notes.md'
    - License: 'about/license.md'
theme:
  name: 'material'
  palette:
    primary: 'red'
  logo: 'images/office.png'
  feature:
    tabs: true
google_analytics:
  - 'UA-110480857-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: http://github.com/SharePoint/office365-cli
edit_uri: blob/master/docs/manual/docs